const states=[['待机',0,6,[280,110,110,140,140,320]],['向右移动',1,8,[120,120,120,120,120,120,120,220]],['向左移动',2,8,[120,120,120,120,120,120,120,220]],['提灯回应',3,4,[140,140,140,280]],['完成反馈',4,5,[140,140,140,140,280]],['任务失败',5,8,[140,140,140,140,140,140,140,240]],['等待输入',6,6,[150,150,150,150,150,260]],['思考与执行',7,6,[120,120,120,120,120,220]],['结果审阅',8,6,[150,150,150,150,150,280]],['视线跟随',9,16,[180]]];
const canvas=document.querySelector('#pet'),ctx=canvas.getContext('2d'),image=new Image();
let current=0,last=0,elapsed=0,cursor=0,look=0,hasGaze=false,hovering=false,sourceCell=384,schedule=[],loopStart=0,scheduleKey='',sequence=[],sequenceElapsed=0;
const mode=()=>document.querySelector('#playback').value;
const buttons=states.map((state,index)=>{const button=document.createElement('button');button.textContent=state[0];button.onclick=()=>{sequence=[];select(index)};document.querySelector('#buttons').append(button);return button});
function select(index){current=index;scheduleKey='';buttons.forEach((button,i)=>button.classList.toggle('active',index===i))}
function resizeCanvas(){const bounds=canvas.getBoundingClientRect(),ratio=window.devicePixelRatio||1;canvas.width=Math.round(bounds.width*ratio);canvas.height=Math.round(bounds.height*ratio);ctx.imageSmoothingQuality='high'}
window.addEventListener('resize',resizeCanvas);resizeCanvas();
function loadSprites(){const quality=document.querySelector('#quality').value,movement=document.querySelector('#movement').value;sourceCell=quality==='hd'?384:192;image.src=quality==='before'?'assets/previews/before-v3.png':`assets/${quality}/${movement}.png`;scheduleKey='';document.querySelector('#error').textContent=''}
for(const name of ['quality','movement','playback'])document.querySelector('#'+name).onchange=loadSprites;
image.onerror=()=>document.querySelector('#error').textContent='素材未能读取。请保留页面与 assets 文件夹的相对位置。';
image.onload=()=>{document.querySelector('#error').textContent='';if(!buttons.some(b=>b.classList.contains('active')))select(0)};
canvas.addEventListener('pointerenter',()=>{hovering=true;scheduleKey=''});canvas.addEventListener('pointerleave',()=>{hovering=false;scheduleKey=''});
document.addEventListener('pointermove',event=>{const bounds=canvas.getBoundingClientRect(),dx=event.clientX-bounds.left-bounds.width/2,dy=event.clientY-bounds.top-bounds.height/2;look=Math.round((Math.atan2(dx,-dy)+2*Math.PI)%(2*Math.PI)/(Math.PI/8))%16;hasGaze=true});
document.querySelector('#sequence').onclick=()=>{sequence=[{state:7,time:2800},{state:6,time:2600},{state:8,time:2600},{state:4,time:1200},{state:0,time:2000}];sequenceElapsed=0;select(sequence[0].state)};
function stateFrames(index){const state=states[index];return Array.from({length:state[2]},(_,column)=>({row:state[1],column,duration:state[3][column%state[3].length]}))}
function buildSchedule(index){const playback=mode(),idle=stateFrames(0);if(index===0){schedule=idle;loopStart=0;return}const row=stateFrames(index);if(playback==='web'){schedule=row;loopStart=0;return}schedule=Array.from({length:3},()=>row).flat().concat(idle);loopStart=row.length*3}
function tick(now){const dt=Math.min(now-last,100);last=now;const playback=mode(),effective=current===9?9:hovering?(playback==='codex'?4:3):current,key=effective+':'+playback;if(effective!==9&&key!==scheduleKey){scheduleKey=key;buildSchedule(effective);cursor=0;elapsed=0}if(!document.querySelector('#pause').checked){const step=dt*Number(document.querySelector('#speed').value);elapsed+=step;if(effective!==9){while(schedule.length&&elapsed>=schedule[cursor].duration){elapsed-=schedule[cursor].duration;cursor++;if(cursor>=schedule.length)cursor=loopStart}}if(sequence.length){sequenceElapsed+=step;if(sequenceElapsed>=sequence[0].time){sequenceElapsed=0;sequence.shift();if(sequence.length)select(sequence[0].state)}}}if(image.complete&&image.naturalWidth){let row=effective===9?9+Math.floor(look/8):schedule[cursor].row,column=effective===9?look%8:schedule[cursor].column;const follows=document.querySelector('#follow').checked&&hasGaze;if(follows&&effective!==9&&playback==='codex'&&!hovering&&[0,3,7].includes(effective)){row=9+Math.floor(look/8);column=look%8}ctx.imageSmoothingEnabled=!(playback==='codex'&&document.querySelector('#quality').value!=='hd');ctx.clearRect(0,0,canvas.width,canvas.height);const height=sourceCell*208/192;ctx.drawImage(image,column*sourceCell,row*height,sourceCell,height,0,0,canvas.width,canvas.height)}document.querySelector('#status').textContent=(hovering&&current!==9?'悬停回应':states[current][0])+' · '+(playback==='codex'?'Codex 宿主节奏':'连续循环');requestAnimationFrame(tick)}
loadSprites();select(0);requestAnimationFrame(tick);
